version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - yo_greek_network

  user_service:
    build: ./user_service
    container_name: user_service
    ports:
      - "8001:8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DB=${MONGODB_USER_DB}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - yo_greek_network

  product_service:
    build: ./product_service
    container_name: product_service
    ports:
      - "8002:8000"
    depends_on:
      - mongodb
      - user_service
    environment:
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DB=${MONGODB_USER_DB}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - yo_greek_network

  order_service:
    build: ./order_service
    container_name: order_service
    ports:
      - "8003:8000"
    depends_on:
      - mongodb
      - user_service
      - product_service
    environment:
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DB=${MONGODB_USER_DB}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - yo_greek_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user_service
      - product_service
      - order_service
    networks:
      - yo_greek_network

networks:
  yo_greek_network:
    driver: bridge

volumes:
  mongodb_data: