services:
  - type: web
    name: yogreek-frontend
    env: nginx
    buildCommand: |
      cd frontend
      rm -rf node_modules .next
      npm install
      npm install -D tailwindcss postcss autoprefixer
      npx tailwindcss init -p
      npm run build
    startCommand: |
      cd frontend
      npm start
    envVars:
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_API_URL
        value: https://yogreek-product-service.onrender.com
      - key: NEXT_PUBLIC_USER_API_URL
        value: https://yogreek-user-service.onrender.com
    healthCheckPath: /
    autoDeploy: true
    nginxConfig: |
      location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
      }

      # Product Service API
      location /api/ {
        proxy_pass https://yogreek-product-service.onrender.com/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
      }

      # User Service API
      location /user_api/ {
        proxy_pass https://yogreek-user-service.onrender.com/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
      }

      # Product Service Admin
      location /admin/ {
        proxy_pass https://yogreek-product-service.onrender.com/admin/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
      }

      # User Service Admin
      location /user_admin/ {
        proxy_pass https://yogreek-user-service.onrender.com/admin/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
      }

      # Static files
      location /static/ {
        alias /opt/render/project/src/frontend/.next/static/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
      }

      # Media files
      location /media/ {
        proxy_pass https://yogreek-product-service.onrender.com/media/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
      }
// ... existing code ...
