services:
  - type: web
    name: yogreek-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://yogreek-product-service.onrender.com

  - type: web
    name: yogreek-product-service
    env: python
    buildCommand: cd ecommerce/product_service && pip install -r requirements.txt
    startCommand: cd ecommerce/product_service && python manage.py migrate && gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DATABASE_URL
        fromDatabase:
          name: yogreek-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: yogreek-product-service.onrender.com

  - type: web
    name: yogreek-user-service
    env: python
    buildCommand: cd ecommerce/user_service && pip install -r requirements.txt
    startCommand: cd ecommerce/user_service && python manage.py migrate && gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DATABASE_URL
        fromDatabase:
          name: yogreek-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: yogreek-user-service.onrender.com

databases:
  - name: yogreek-db
    databaseName: yogreek
    user: yogreek
    plan: free 
